# ==========    GENERAL    ==========

profile=high-quality                            # Allows for higher quality playback on mpv
vo=gpu-next                                     # https://mpv.io/manual/stable/#video-output-drivers-gpu

# gpu-api=vulkan offers better overall performance, but it sometimes breaks playback
# For displaying HDR content (not HDR -> SDR) "d3d11" is recommended (Windows only)
gpu-api=vulkan                                  # https://mpv.io/manual/stable/#options-gpu-api
fullscreen=yes                                  # Start in fullscreen
keep-open=always                                # Don't close the player after finishing the video,
                                                # and playback will never automatically advance to the next file in the playlist
hwdec=vulkan                                    # https://mpv.io/manual/stable/#options-hwdec
scale=ewa_lanczossharp                          # Luma upscaler
dscale=mitchell                                 # Luma downscaler
cscale=ewa_lanczossharp                         # Chroma up&downscaler
gpu-shader-cache-dir='~~/shaders/cache'         # https://mpv.io/manual/stable/#options-gpu-shader-cache-dir


# ==========    DEBANDING    ==========

# Banding is a visual artifact, visual artifacts should never be in a video. 
# Example of banding: https://imgur.com/32d77H0
# Debanding is the process of removing said banding.
# 6 minute explanation of what causes banding: https://www.youtube.com/watch?v=h9j89L8eQQk

deband=no                                       # Turn on only for videos with banding. (Keybind=d)
deband-iterations=2                             # https://mpv.io/manual/stable/#options-deband-iterations
deband-threshold=64                             # https://mpv.io/manual/stable/#options-deband-threshold
deband-range=17                                 # https://mpv.io/manual/stable/#options-deband-range
deband-grain=12                                 # https://mpv.io/manual/stable/#options-deband-grain


# ==========    LANGUAGE PRIORITY    ==========

alang=ja,jp,jpn                                 # Audio language priority
slang=ru,rus,en,eng                             # Subtitle language priority


# ==========    AUDIO    ==========

volume=100                                      # default volume, 100 = unchanged
audio-file-auto=fuzzy                           # Load external audio with (almost) the same name as the video
volume-max=200                                  # Max volume of the player
audio-pitch-correction=yes                      # https://mpv.io/manual/stable/#options-audio-pitch-correction


# ==========    SUBTITLES    ==========

demuxer-mkv-subtitle-preroll=yes                # https://mpv.io/manual/stable/#options-demuxer-mkv-subtitle-preroll
sub-fix-timing=no                               # https://mpv.io/manual/stable/#options-sub-fix-timing
sub-auto=fuzzy                                  # https://mpv.io/manual/stable/#options-sub-auto


# ==========    SCREENSHOT    ==========

screenshot-format=png                           # Output format of screenshots
screenshot-high-bit-depth=yes                   # Same output bitdepth as the video. Set it "no" if you want to save disc space
screenshot-png-compression=1                    # Compression of the PNG picture (1-9).
                                                # Higher value means better compression, but takes more time
screenshot-directory="~/Pictures/mpv-screenshots"           # Output directory
screenshot-template="%f-%wH.%wM.%wS.%wT-#%#00n"             # Name format (filename-hour-minute-second-milisecond-number)
